
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mustafa
 */
public class Customers extends javax.swing.JFrame {
DBM db = new DBM();

    /**
     * Creates new form Customers
     */
    public Customers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CustAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CustInfo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CustName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        CustID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(CustID);
        CustID.setBounds(280, 170, 60, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Customer ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 170, 120, 50);

        CustAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(CustAddress);
        CustAddress.setBounds(280, 380, 330, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 380, 120, 50);

        CustInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(CustInfo);
        CustInfo.setBounds(280, 310, 330, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Contact Info");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 310, 120, 50);

        CustName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(CustName);
        CustName.setBounds(280, 240, 330, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Customer Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 240, 140, 50);

        Add.setText("Add");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(850, 300, 100, 60);

        Update.setText("Update");
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(850, 370, 100, 60);

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(850, 230, 100, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Customers");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 10, 240, 120);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 120, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
Add.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
                String id = CustID.getText();
        String name = CustName.getText();
        String contact = CustInfo.getText();
        String address = CustAddress.getText();

        String sql = "INSERT INTO CUSTOMERS (CUSTID, CUSTNAME, CUSTCONTACT, CUSTADDRESS) " +
                     "VALUES ('" + id + "', '" + name + "', '" + contact + "', '" + address + "')";

        String result = db.runInsUpDel(sql);
        if (result.equals("OK")) {
            JOptionPane.showMessageDialog(null, "Customer Added");
        } else {
            JOptionPane.showMessageDialog(null, result);
        }
    }
});
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
Search.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        String id = CustID.getText();
        String sql = "SELECT * FROM CUSTOMERS WHERE CUSTID = '" + id + "'";
        ResultSet rs = db.runSelect(sql);
        
        try {
            if (rs != null && rs.next()) {
                CustName.setText(rs.getString("CUSTNAME"));
                CustInfo.setText(rs.getString("CUSTCONTACT"));
                CustAddress.setText(rs.getString("CUSTADDRESS"));
            } else {
                JOptionPane.showMessageDialog(null, "No record found");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
});
    }//GEN-LAST:event_SearchActionPerformed

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
String id = CustID.getText();
        String name = CustName.getText();
        String contact = CustInfo.getText();
        String address = CustAddress.getText();

        String sql = "UPDATE CUSTOMERS SET CUSTNAME = '" + name + 
                     "', CUSTCONTACT = '" + contact + 
                     "', CUSTADDRESS = '" + address + 
                     "' WHERE CUSTID = '" + id + "'";

        String result = db.runInsUpDel(sql);
        if (result.equals("OK")) {
            JOptionPane.showMessageDialog(null, "Customer Updated");
        } else {
            JOptionPane.showMessageDialog(null, result);
        }
    
    }//GEN-LAST:event_UpdateMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField CustAddress;
    private javax.swing.JTextField CustID;
    private javax.swing.JTextField CustInfo;
    private javax.swing.JTextField CustName;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
