
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mustafa
 */
public class Login extends javax.swing.JFrame {
DBM db = new DBM();
    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pass_lbl = new javax.swing.JLabel();
        pass_in = new javax.swing.JPasswordField();
        usr_lbl = new javax.swing.JLabel();
        usr_in = new javax.swing.JTextField();
        usr_lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Login");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 260, 90));

        pass_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pass_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass_lbl.setText("Password");
        getContentPane().add(pass_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 100, 70));

        pass_in.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(pass_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 340, 70));

        usr_lbl.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        usr_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usr_lbl.setText("Login to proceed");
        getContentPane().add(usr_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 430, 120));

        usr_in.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(usr_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 340, 70));

        usr_lbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usr_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usr_lbl1.setText("User Name");
        getContentPane().add(usr_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 100, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
  String usr = usr_in.getText();
        String pass = new String(pass_in.getPassword());
        String sql = "SELECT EMPPASSWORD FROM EMPLOYEE WHERE EMPUSERNAME = '" + usr + "'";
        ResultSet set = db.runSelect(sql);
        
        
        try{
        if(set != null && set.next()){
            String db_pass = set.getString("EMPPASSWORD");
            if(pass.equals(db_pass)){
                new Home().setVisible(true);
                dispose();
                
            }else{
                JOptionPane.showMessageDialog(null, "User name or password is incorrect");
            }
        }else{
        JOptionPane.showMessageDialog(null, "User name or password is incorrect");
        }
            
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField pass_in;
    private javax.swing.JLabel pass_lbl;
    private javax.swing.JTextField usr_in;
    private javax.swing.JLabel usr_lbl;
    private javax.swing.JLabel usr_lbl1;
    // End of variables declaration//GEN-END:variables
}
