
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mustafa
 */
public class Products extends javax.swing.JFrame {
DBM db = new DBM();

    public Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ProdID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SupID = new javax.swing.JTextField();
        ArvDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        InStock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ProdName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ExpDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 120, 50);

        ProdID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(ProdID);
        ProdID.setBounds(280, 170, 60, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Product ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 170, 120, 50);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Supplier ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(430, 170, 120, 50);

        SupID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(SupID);
        SupID.setBounds(550, 170, 60, 50);

        ArvDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(ArvDate);
        ArvDate.setBounds(280, 380, 330, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Arrival date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 380, 120, 50);

        InStock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(InStock);
        InStock.setBounds(280, 310, 330, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("In Stock");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 310, 120, 50);

        ProdName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(ProdName);
        ProdName.setBounds(280, 240, 330, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Product name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 240, 140, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Expiration Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 450, 130, 50);

        ExpDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(ExpDate);
        ExpDate.setBounds(280, 450, 330, 50);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Price");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 520, 120, 50);

        Price.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(Price);
        Price.setBounds(280, 520, 330, 50);

        Add.setText("Add");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(870, 330, 100, 60);

        Update.setText("Update");
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(870, 400, 100, 60);

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(870, 260, 100, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Products");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 10, 240, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
 Add.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            // Retrieve data from text fields
            String prodId = ProdID.getText();
            String prodName = ProdName.getText();
            String inStock = InStock.getText();
            String arrDate = ArvDate.getText(); // Expected format: 'YYYY-MM-DD'
            String expDate = ExpDate.getText(); // Expected format: 'YYYY-MM-DD'
            String price = Price.getText();
            String supId = SupID.getText();

            // Create SQL query to insert into PRODUCT table
            String sql = "INSERT INTO PRODUCT (PRODID, PRODNAME, INSTOCK, ARVDATE, EXPDATE, PRICE, SUPID) " +
                         "VALUES ('" + prodId + "', '" + prodName + "', " + inStock + ", TO_DATE('" + arrDate + "', 'YYYY-MM-DD'), " +
                         "TO_DATE('" + expDate + "', 'YYYY-MM-DD'), " + price + ", '" + supId + "')";

            // Execute the query and get the result
            String result = db.runInsUpDel(sql);

            // Display result
            if (result.equals("OK")) {
                JOptionPane.showMessageDialog(null, "Product Added");
            } else {
                JOptionPane.showMessageDialog(null, result);
            }
    }
});
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
Search.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        String id = ProdID.getText();  // Get the product ID from the ProdID text field
        String sql = "SELECT * FROM PRODUCT WHERE PRODID = '" + id + "'";  // SQL query to fetch product data
        
        // Execute the select query
        ResultSet rs = db.runSelect(sql);
        
        try {
            // Check if there is a result
            if (rs != null && rs.next()) {
                // Set the values in the respective text fields
                ProdName.setText(rs.getString("PRODNAME"));
                InStock.setText(rs.getString("INSTOCK"));
                ArvDate.setText(rs.getString("ARVDATE"));
                ExpDate.setText(rs.getString("EXPDATE"));
                Price.setText(rs.getString("PRICE"));
                SupID.setText(rs.getString("SUPID"));
            } else {
                // If no record is found
                JOptionPane.showMessageDialog(null, "No record found");
            }
        } catch (SQLException ex) {
            // Handle any SQL exceptions
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
});

    }//GEN-LAST:event_SearchActionPerformed

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
String id = ProdID.getText();
String name = ProdName.getText();
String stock = InStock.getText();
String arvDate = ArvDate.getText();
String expDate = ExpDate.getText();
String price = Price.getText();
String supID = SupID.getText();

// SQL query to update product information
String sql = "UPDATE PRODUCT SET PRODNAME = '" + name + 
             "', INSTOCK = " + stock + 
             ", ARVDATE = TO_DATE('" + arvDate + "', 'YYYY-MM-DD')" +
             ", EXPDATE = TO_DATE('" + expDate + "', 'YYYY-MM-DD')" +
             ", PRICE = " + price + 
             ", SUPID = '" + supID + 
             "' WHERE PRODID = '" + id + "'";

// Run the query
String result = db.runInsUpDel(sql);
if (result.equals("OK")) {
    JOptionPane.showMessageDialog(null, "Product Updated");
} else {
    JOptionPane.showMessageDialog(null, result);
}

    }//GEN-LAST:event_UpdateMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField ArvDate;
    private javax.swing.JTextField ExpDate;
    private javax.swing.JTextField InStock;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField ProdID;
    private javax.swing.JTextField ProdName;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SupID;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
